services:
  # Redis Stack (JSON機能付き)
  redis:
    image: redis/redis-stack:latest
    container_name: distributed-redis
    ports:
      - "6379:6379"      # Redis接続ポート
      - "8001:8001"      # RedisInsight (Redis GUI)
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - distributed-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: distributed-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rusted_ca
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - distributed-network

  # phpMyAdmin (MySQL管理ツール)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: distributed-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - distributed-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  distributed-network:
    driver: bridge
    name: distributed-storage-network